### ISSUE TITLE
java 代码解析报错，写法不兼容；

### ISSUE THREAD

**Issue by DarkIdiot** [baikaishuipp/jcci#37]
** 描述问题 **
import javalang
from pip._internal.utils import logging

text = '''
import kz.greetgo.gcoll.register.util.mysql;;
import kz.greetgo.gcoll.register.util.mysql;

'''

try:
    tree = javalang.parse.parse(text)
except Exception as e:
    logging.error(f"Error parsing : {e}")

** 提供信息 **
1. JCCI的版本/分支
2. python 的版本
3. A->B链路断了反馈：当前A节点截图、类名(com.XXX.XX.AClass)，调用A节点的B方法截图（包含调用A地方)、类名(com.XXX.XX.BClass)、B方法节点的method_invocation_map：（select method_invocation_map from methods where method_name='B')
4. 控制台日志文件
Traceback (most recent call last):
  File "D:\python\rpa\jcci\src\test.py", line 11, in <module>
    tree = javalang.parse.parse(text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\rpa\jcci\.venv\Lib\site-packages\javalang\parse.py", line 53, in parse
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "D:\python\rpa\jcci\.venv\Lib\site-packages\javalang\parser.py", line 110, in parse
    return self.parse_compilation_unit()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\rpa\jcci\.venv\Lib\site-packages\javalang\parser.py", line 302, in parse_compilation_unit
    type_declaration = self.parse_type_declaration()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\rpa\jcci\.venv\Lib\site-packages\javalang\parser.py", line 347, in parse_type_declaration
    return self.parse_class_or_interface_declaration()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\rpa\jcci\.venv\Lib\site-packages\javalang\parser.py", line 364, in parse_class_or_interface_declaration
    self.illegal("Expected type declaration")
  File "D:\python\rpa\jcci\.venv\Lib\site-packages\javalang\parser.py", line 119, in illegal
    raise JavaSyntaxError(description, at)
javalang.parser.JavaSyntaxError

**Comment by baikaishuipp** [comment]
我的库不是这样用的吧，这个报错是javalang抛的

**Comment by DarkIdiot** [comment]
这个我处理了， 兼容了
